### ISSUE TITLE
has anyone done the test?

### ISSUE THREAD

**Issue by juanpc2018** [samowitsch/minimig-arm-controller-0805#1]
since this mod is only  for the original minimig v1.3
https://www.techtravels.org/wp-content/uploads/pefiles/minimig/weeren001/home.html
https://www.minimig.ca/index.php/2021/07/19/minimig-v1-3/

has anyone tested:
Minimig 1.3 + ARM 
vs.
New Minimig https://www.minimig.ca/
vs.
MIST https://lotharek.pl/productdetail.php?id=45
vs. 
MISTer ?

**Comment by samowitsch** [comment]
That's not really a issue. Rather a performance question for a amiga retro forum.
Personally, i only own a Minimig V1.1 with ARM controller and have no comparison to other solutions.
